steps:

- id: 'Exec unit tests'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', 'app']
  env: 
    - 'GOPATH=./go'

- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/fullcycle-k8s-go', './go']

images: ['gcr.io/$PROJECT_ID/fullcycle-k8s-go']