apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullcycle-k8s-go-deployment
spec:
  replicas: 1

  selector: # usado pelo service
    matchLabels:
      app: fullcycle-k8s-go-server
  
  template:
    metadata:
      labels: 
        app: fullcycle-k8s-go-server
    spec:
      containers:
        - image: softplayers/fullcycle-k8s-go
          name: fullcycle-k8s-go
          ports:
            - containerPort: 8000

